name: rdf_mapper
version: 0.1.0
homepage: https://github.com/yourusername/rdf_mapper
description: >
  ORM-like mapping between plain Dart classes and RdfGraph from rdf_core. Companion library for https://pub.dev/packages/rdf_core.
environment:
  sdk: '^3.7.0'
dependencies:
  rdf_core: ^0.1.2

dev_dependencies:
  test: ^1.16.0
