// Mocks generated by Mockito 5.4.6 from annotations
// in rdf_mapper/test/src/deserializers/iri_term_deserializer_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:rdf_core/rdf_core.dart' as _i3;
import 'package:rdf_mapper/src/api/deserialization_context.dart' as _i2;
import 'package:rdf_mapper/src/api/deserializer.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DeserializationContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeserializationContext extends _i1.Mock
    implements _i2.DeserializationContext {
  MockDeserializationContext() {
    _i1.throwOnMissingStub(this);
  }

  @override
  T require<T>(
    _i3.RdfSubject? subject,
    _i3.RdfPredicate? predicate, {
    bool? enforceSingleValue = true,
    _i4.IriSubjectGraphDeserializer<T>? subjectDeserializer,
    _i4.IriTermDeserializer<T>? iriDeserializer,
    _i4.LiteralTermDeserializer<T>? literalDeserializer,
    _i4.BlankNodeSubjectGraphDeserializer<T>? blankNodeDeserializer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #require,
              [subject, predicate],
              {
                #enforceSingleValue: enforceSingleValue,
                #subjectDeserializer: subjectDeserializer,
                #iriDeserializer: iriDeserializer,
                #literalDeserializer: literalDeserializer,
                #blankNodeDeserializer: blankNodeDeserializer,
              },
            ),
            returnValue: _i5.dummyValue<T>(
              this,
              Invocation.method(
                #require,
                [subject, predicate],
                {
                  #enforceSingleValue: enforceSingleValue,
                  #subjectDeserializer: subjectDeserializer,
                  #iriDeserializer: iriDeserializer,
                  #literalDeserializer: literalDeserializer,
                  #blankNodeDeserializer: blankNodeDeserializer,
                },
              ),
            ),
          )
          as T);

  @override
  T? get<T>(
    _i3.RdfSubject? subject,
    _i3.RdfPredicate? predicate, {
    bool? enforceSingleValue = true,
    _i4.IriTermDeserializer<T>? iriDeserializer,
    _i4.IriSubjectGraphDeserializer<T>? subjectDeserializer,
    _i4.LiteralTermDeserializer<T>? literalDeserializer,
    _i4.BlankNodeSubjectGraphDeserializer<T>? blankNodeDeserializer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [subject, predicate],
              {
                #enforceSingleValue: enforceSingleValue,
                #iriDeserializer: iriDeserializer,
                #subjectDeserializer: subjectDeserializer,
                #literalDeserializer: literalDeserializer,
                #blankNodeDeserializer: blankNodeDeserializer,
              },
            ),
          )
          as T?);

  @override
  R getMany<T, R>(
    _i3.RdfSubject? subject,
    _i3.RdfPredicate? predicate,
    R Function(Iterable<T>)? collector, {
    _i4.IriTermDeserializer<T>? iriDeserializer,
    _i4.IriSubjectGraphDeserializer<T>? subjectDeserializer,
    _i4.LiteralTermDeserializer<T>? literalDeserializer,
    _i4.BlankNodeSubjectGraphDeserializer<T>? blankNodeDeserializer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMany,
              [subject, predicate, collector],
              {
                #iriDeserializer: iriDeserializer,
                #subjectDeserializer: subjectDeserializer,
                #literalDeserializer: literalDeserializer,
                #blankNodeDeserializer: blankNodeDeserializer,
              },
            ),
            returnValue: _i5.dummyValue<R>(
              this,
              Invocation.method(
                #getMany,
                [subject, predicate, collector],
                {
                  #iriDeserializer: iriDeserializer,
                  #subjectDeserializer: subjectDeserializer,
                  #literalDeserializer: literalDeserializer,
                  #blankNodeDeserializer: blankNodeDeserializer,
                },
              ),
            ),
          )
          as R);

  @override
  List<T> getList<T>(
    _i3.RdfSubject? subject,
    _i3.RdfPredicate? predicate, {
    _i4.IriTermDeserializer<T>? iriDeserializer,
    _i4.IriSubjectGraphDeserializer<T>? subjectDeserializer,
    _i4.LiteralTermDeserializer<T>? literalDeserializer,
    _i4.BlankNodeSubjectGraphDeserializer<T>? blankNodeDeserializer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getList,
              [subject, predicate],
              {
                #iriDeserializer: iriDeserializer,
                #subjectDeserializer: subjectDeserializer,
                #literalDeserializer: literalDeserializer,
                #blankNodeDeserializer: blankNodeDeserializer,
              },
            ),
            returnValue: <T>[],
          )
          as List<T>);

  @override
  Map<K, V> getMap<K, V>(
    _i3.RdfSubject? subject,
    _i3.RdfPredicate? predicate, {
    _i4.IriTermDeserializer<MapEntry<K, V>>? iriDeserializer,
    _i4.IriSubjectGraphDeserializer<MapEntry<K, V>>? subjectDeserializer,
    _i4.LiteralTermDeserializer<MapEntry<K, V>>? literalDeserializer,
    _i4.BlankNodeSubjectGraphDeserializer<MapEntry<K, V>>?
    blankNodeDeserializer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMap,
              [subject, predicate],
              {
                #iriDeserializer: iriDeserializer,
                #subjectDeserializer: subjectDeserializer,
                #literalDeserializer: literalDeserializer,
                #blankNodeDeserializer: blankNodeDeserializer,
              },
            ),
            returnValue: <K, V>{},
          )
          as Map<K, V>);
}
